server:
  port: ${PORT:8080}
# Ensure application is run in Vaadin 14/npm mode
vaadin:
  compatibilityMode: false
logging.level:
  org.atmosphere: warn
# To improve the performance during development.
# ----------------
# Orphan comments:
# ----------------
# Was at begin of line:10 :# For more information https://vaadin.com/docs/v14/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
# Was at begin of line:11 :# vaadin.whitelisted-packages= org/vaadin/example

spring.datasource:
  url: jdbc:h2:mem:productdb
  platform: h2
  driverClassName: org.h2.Driver
  username: sa
  password: 
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2.console:
    enabled: true
    path: h2-console