export enum EditProductActionNames {
  EDIT_PRODUCT_BEGIN = "EDIT_PRODUCT_BEGIN",
  EDIT_PRODUCT_SAVE = "EDIT_PRODUCT_SAVE",
  EDIT_PRODUCT_ABORT = "EDIT_PRODUCT_ABORT",
  EDIT_PRODUCT_EDIT = "EDIT_PRODUCT_EDIT",
}

export enum ProductListActionNames {
  PRODUCT_LIST_COMPLETE_LOADING = "PRODUCT_LIST_COMPLETE_LOADING",
  PRODUCT_LIST_REMOVE_ELEMENTS = "PRODUCT_LIST_REMOVE_ELEMENTS",
  PRODUCT_LIST_UPDATE_ELEMENTS = "PRODUCT_LIST_UPDATE_ELEMENTS",
}
